### ISSUE TITLE
https://github.com/vortexau/dnsvalidator.git SYNTAX ERROR

### ISSUE THREAD

**Issue by machinexa2** [vortexau/dnsvalidator#22]
dnsvalidator -h
Traceback (most recent call last):
  File "/usr/local/bin/dnsvalidator", line 11, in <module>
    load_entry_point('DNSValidator==0.1', 'console_scripts', 'dnsvalidator')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "build/bdist.linux-x86_64/egg/dnsvalidator/dnsvalidator.py", line 15, in <module>
  File "/usr/local/lib/python2.7/dist-packages/DNSValidator-0.1-py2.7.egg/dnsvalidator/lib/core/input.py", line 50
    parser.error(f"Tried to fetch {arg} but got {e} are you sure this is a valid URL?")
                                                                                     ^
SyntaxError: invalid syntax
root@kali-linux:~/BugBounty/Tools/dnsvalidator# dnsvalidator --help
Traceback (most recent call last):
  File "/usr/local/bin/dnsvalidator", line 11, in <module>
    load_entry_point('DNSValidator==0.1', 'console_scripts', 'dnsvalidator')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "build/bdist.linux-x86_64/egg/dnsvalidator/dnsvalidator.py", line 15, in <module>
  File "/usr/local/lib/python2.7/dist-packages/DNSValidator-0.1-py2.7.egg/dnsvalidator/lib/core/input.py", line 50
    parser.error(f"Tried to fetch {arg} but got {e} are you sure this is a valid URL?")
                                                                                     ^
SyntaxError: invalid syntax
root@kali-linux:~/BugBounty/Tools/dnsvalidator# dnsvalidator 
Traceback (most recent call last):
  File "/usr/local/bin/dnsvalidator", line 11, in <module>
    load_entry_point('DNSValidator==0.1', 'console_scripts', 'dnsvalidator')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "build/bdist.linux-x86_64/egg/dnsvalidator/dnsvalidator.py", line 15, in <module>
  File "/usr/local/lib/python2.7/dist-packages/DNSValidator-0.1-py2.7.egg/dnsvalidator/lib/core/input.py", line 50
    parser.error(f"Tried to fetch {arg} but got {e} are you sure this is a valid URL?")
                                                                                     ^
SyntaxError: invalid syntax
root@kali-linux:~/BugBounty/Tools/dnsvalidator# C

**Comment by darkmachineweb** [comment]
I noticed requirements.txt doesnt have InputParser package

**Comment by darkmachineweb** [comment]
root@kali-linux:~/BugBounty/Tools/dnsvalidator/dnsvalidator# python3 dns*.py
Traceback (most recent call last):
  File "dnsvalidator.py", line 15, in <module>
    from .lib.core.input import InputParser, InputHelper
ImportError: attempted relative import with no known parent package

**Comment by darkmachineweb** [comment]
root@kali-linux:~/BugBounty/Tools/dnsvalidator/dnsvalidator# pip install InputParser
Collecting InputParser
Could not install packages due to an EnvironmentError: 404 Client Error: Not Found for url: https://pypi.org/simple/inputparser/
                                                                                                                                                    
root@kali-linux:~/BugBounty/Tools/dnsvalidator/dnsvalidator#

**Comment by m3chj0ker** [comment]
Hi,

I just installed dnsvalidator and had the same issue. I am not associated with this project but have managed to get it working and found out what was the root cause.

The string within the "parse.error" call is using f-string formatting, this is formatting has only been introduced since Python v3.6 so for all versions prior is triggering an error when being imported.

So to get dnsvalidator working either upgrade to a version greater than 3.6 or a work around if you must keep your current version would be to change the f string format in the init.py file.

i.e:  parser.error(f"Tried to fetch {arg} but got {e} are you sure this is a valid URL?")
to parser.error(f"Tried to fetch %s but got %s are you sure this is a valid URL?" % (arg,e))

**Comment by machinexa2** [comment]
oh i dont know how but it works now
