### ISSUE TITLE
dns.resolver.NoNameservers: All nameservers failed to answer the query bet365.com. IN A: Server 1.1.1.1 UDP port 53 answered [Errno 101] Network is unreachable

### ISSUE THREAD

**Issue by SandeshAjgekar** [vortexau/dnsvalidator#33]
HI,
I am trying to run command -
dnsvalidator -tL https://public-dns.info/nameservers.txt -threads 100 -o resolvers.txt 

but its showing this error -

[05:45:52] [INFO] [1.1.1.1] resolving baseline
Traceback (most recent call last):
  File "/usr/local/bin/dnsvalidator", line 33, in <module>
    sys.exit(load_entry_point('DNSValidator==0.1', 'console_scripts', 'dnsvalidator')())
  File "/usr/local/lib/python3.9/dist-packages/DNSValidator-0.1-py3.9.egg/dnsvalidator/dnsvalidator.py", line 120, in main
  File "/usr/lib/python3/dist-packages/dns/resolver.py", line 1089, in query
    return self.resolve(qname, rdtype, rdclass, tcp, source,
  File "/usr/lib/python3/dist-packages/dns/resolver.py", line 1040, in resolve
    (nameserver, port, tcp, backoff) = resolution.next_nameserver()
  File "/usr/lib/python3/dist-packages/dns/resolver.py", line 598, in next_nameserver
    raise NoNameservers(request=self.request, errors=self.errors)
dns.resolver.NoNameservers: All nameservers failed to answer the query bet365.com. IN A: Server 1.1.1.1 UDP port 53 answered [Errno 101] Network is unreachable

I verified my network was fine. not able to resolve the issue. please help

**Comment by MShaheer15** [comment]
me with the same issue does anybody know the solution
