### ISSUE TITLE
DNS Timeout exception not handled in baseline checks.

### ISSUE THREAD

**Issue by vortexau** [vortexau/dnsvalidator#8]
When querying DNS servers, occasionally a 30 second timeout is encountered (UDP gonna UDP!) and the exception generated is not handled correctly.

Example:
```
[21:51:50] [INFO] [1.1.1.1] resolving baseline
[21:51:55] [INFO] [8.8.8.8] resolving baseline
Traceback (most recent call last):
  File "/usr/local/bin/dnsvalidator", line 11, in <module>
    load_entry_point('DNSValidator==0.1', 'console_scripts', 'dnsvalidator')()
  File "/usr/local/lib/python3.7/dist-packages/DNSValidator-0.1-py3.7.egg/dnsvalidator/dnsvalidator.py", line 134, in main
  File "/usr/lib/python3/dist-packages/dns/resolver.py", line 992, in query
    timeout = self._compute_timeout(start, lifetime)
  File "/usr/lib/python3/dist-packages/dns/resolver.py", line 799, in _compute_timeout
    raise Timeout(timeout=duration)
dns.exception.Timeout: The DNS operation timed out after 30.00101947784424 seconds
```

**Comment by vortexau** [comment]
Resolved by b55b6f0
